version: 2
updates:
  # - package-ecosystem: "pip"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/{{cookiecutter.repo_dir}}"
    schedule:
      interval: "weekly"