name: CI

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Run static analysis and lint checker via Docker Compose
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.ci.yml

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Create .env file from sample
        run: cp .env.sample .env

      - name: Build Docker image with retry
        run: |
          success=0
          for i in 1 2 3; do
            docker compose build && success=1 && break
            echo "Docker compose build failed... retrying ($i/3)"
            sleep 10
          done
          if [ "$success" -eq 0 ]; then
            echo "Docker compose build failed after 3 attempts."
            exit 1
          fi

      - name: Run pre-commit checks
        run: docker compose run -T --rm {{ cookiecutter.package_dir }} pre-commit run --all-files

  test:
    name: Run pytest via Docker Compose
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.ci.yml

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Create .env file from sample
        run: cp .env.sample .env

      - name: Build Docker image with retry
        run: |
          success=0
          for i in 1 2 3; do
            docker compose build && success=1 && break
            echo "Docker compose build failed... retrying ($i/3)"
            sleep 10
          done
          if [ "$success" -eq 0 ]; then
            echo "Docker compose build failed after 3 attempts."
            exit 1
          fi

      - name: Run tests with coverage reports
        run: docker compose run -T --rm {{ cookiecutter.package_dir }} pytest --cov --cov-report xml --cov-report term-missing